apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: spring-boot-helloworld-s2i
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring-boot-helloworld-s2i
spec: 
  output:
    to:
      kind: "ImageStreamTag"
      name: "spring-boot-helloworld-s2i:latest"
  source:
    git:
      ref: master
      uri: https://github.com/DaniellaFreese/spring-boot-helloworld.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: BUILD_LOGLEVEL
        value: "5"
      - name: ARTIFACT_DIR
      - name: MAVEN_ARGS
        value: package -DskipTests -e -B
      - name: MAVEN_ARGS_APPEND
      forcePull: true
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-8:1.3
        namespace: openshift
      incremental: true
